### ISSUE TITLE
dy is not calculated correctly

### ISSUE THREAD

**Issue by Vandoo** [boutproject/hypnotoad#107]
total(dy) = 10.77, not 6.28.
>        # constant spacing in y for now
>         if self.ny_core > 0:
>             # If there is a core region, set dy consistent with 0<=y<2pi in the core
>            self.dy_scalar = 2.0 * numpy.pi / self.ny_core
>         else:
>             # No core region, set dy consistent with 0<=y<2pi in whole domain
>             self.dy_scalar = 2.0 * numpy.pi / self.ny_noguards

For my test ny_... = 8/24/8/12/32/16, dy should be: 2*np.pi/96=0.065. 
But grid['dy']=0.1122. It seems only to count the outer half, 2*np.pi/(16*2+32)=0.1122.

**Comment by johnomotani** [comment]
The calculation is like the comments say - `dy` is chosen so that 'y' goes from 0 to 2*pi around the core region (not the whole grid including divertor legs). So your dy=2*pi/(24+32)=0.112.
`dy` is set from `dy_scalar` https://github.com/boutproject/hypnotoad/blob/c37affb3fb630fcdcf4383ab5c4bfdd5155fd801/hypnotoad/core/mesh.py#L970-L974
and then hy (which is ds/dy where ds is the arc length in the poloidal plane along a flux surface) is calculated using `dy` https://github.com/boutproject/hypnotoad/blob/c37affb3fb630fcdcf4383ab5c4bfdd5155fd801/hypnotoad/core/mesh.py#L1535
and `hy` is used to calculate the metric components, etc. So although the definition of 'y' is rescaled compared to the IDL hypnotoad, the physically relevant quantities are not affected by the change - see discussion in #51.

**Comment by johnomotani** [comment]
This should not be the reason. The changed definition of `dy` does not change any physical quantities:

https://github.com/boutproject/hypnotoad/pull/51#issuecomment-652405608
> Note that because (https://github.com/boutproject/hypnotoad/issues/49#issuecomment-651073736)
> > Apparently the old hypnotoad is also 0 -> 2pi in ny, not in the core
>
> After this PR, dy and various metric coeffiecients, etc. will be rescaled significantly compared to the original hypnotoad (currently smaller difference are just due to slightly differently chosen grid-point positions or accuracy of interpolations, etc.). If `f = ny_core/ny` is the rescaling factor:
> * `dy = f*dy_old`
> * `hy = hthe_old/f`
> * `J = J_old/f`
> * `g22 = g22_old*f**2`
> * `g12 = g12_old*f`
> * `g23 = g23_old*f`
> * `g_22 = g_22_old/f**2`
> * `g_12 = g_12_old/f`
> * `g_23 = g_23_old/f`
> * `curl_bOverB_y = curl_bOverB_y_old*f`

https://github.com/boutproject/hypnotoad/pull/51#issuecomment-652407155
> Very possibly a stupid question, but does that end up changing the physical size of the domain?

https://github.com/boutproject/hypnotoad/pull/51#issuecomment-652417100
> No, I'm pretty sure (I read through all the places `dy` and `hy` are used) that it doesn't change the physical size of the grid. The scaling of the `y` coordinate was just an arbitrary choice in the first place, and everywhere it is used the rescaling here should cancel out - e.g. `Grad_par(A) = DDY(A)/sqrt(g_22) = index_DDY(A)/dy/sqrt(g_22)` and so the scaling factor `f` that I defined in my previous comment cancels between `dy` and `sqrt(g_22)`.

https://github.com/boutproject/hypnotoad/pull/51#issuecomment-652418411
> I think this is right; `y` is an arbitrary choice of coordinate. The physical poloidal distance `lpol` is related to `dy` by the scale factor `hthe`. As long as `hthe * dy` is constant then the physical size of the grid is unchanged.

**Comment by bendudson** [comment]
Hi @Vandoo As @johnomotani says, `dy` by itself isn't a physically meaningful quantity; it's an arbitrary poloidal coordinate. The arc length between cells is physically meaningful, and is given by `dy * hthe`

**Comment by Vandoo** [comment]
Thanks!  Then in order to keep `dy * hthe` the same, it means `hthe` will change accordingly. It would change `g_22, g22, g23, g_23, J` and `bxcvx, bxcvy, bxcvz`, etc?

**Comment by Vandoo** [comment]
Thanks!
