### ISSUE TITLE
Definition of dy in the core

### ISSUE THREAD

**Issue by bendudson** [boutproject/hypnotoad#49]
Following discussion with H.Seto, it would be useful for post-processing if dy was defined so that y went from 0 to 2pi in the core region of tokamak grids. Is there a way to do this, while allowing for cases like Torpex where there isn't a core region?

**Comment by johnomotani** [comment]
Temporary workaround - `dy` is always constant, so it's fine to just shift and rescale as something like `theta = (y - y[jyseps1_1])*(jyseps2_1 - jyseps1_1 + jyseps2_2 - jyseps1_2)/ny`.

Agree it would be nice and more consistent with original hypnotoad to define y so it's 0->2pi in the core. Will have to have a look at how easy this is to do...

**Comment by bendudson** [comment]
Apparently the old hypnotoad is also 0 -> 2pi in ny, not in the core (I had forgotten this). The scaling should be fine, as long as hthe and the metrics are scaled in a consistent way.

**Comment by HarukiST** [comment]
For IDL hypnotoad,  poloidal label y may be from 0 to 2pi in the core if we use ny_core = jyseps2_1 - jyseps1_1 + 
jyseps2_2 - jyseps1_2 rather than ny to define  dtheta in line 803 in process _grid.pro 

https://github.com/boutproject/BOUT-dev/blob/85c53082cf49a74d32c13a504537e27a43a14bbe/tools/tokamak_grids/gridgen/process_grid.pro#L803

Relating to this issue, output of IDL hypnotoad has a 2D array of poloidal angle of straight-field-line coordinates "pol_angle" but doesn't have poloidal angle of orthogonal flux coordinates. 

https://github.com/boutproject/BOUT-dev/blob/85c53082cf49a74d32c13a504537e27a43a14bbe/tools/tokamak_grids/gridgen/process_grid.pro#L1155 

The pol_angle is defined to be from 0 to 2pi in the core region while  y in the core is not defined to be from 0 to 2pi.
But this gives no conflicts since label y and pol_angle have a one-to-one correspondence.

**Comment by johnomotani** [comment]
It is pretty simple to change the definition of `dy` to be consistent with a `y`-coordinate that goes from 0->2pi in the core rather than across the whole domain. `hy` and metrics are calculated from `dy` so will be consistent with it.

I don't think there are y-coordinate or poloidal angle outputs yet. They might be nice to have... Question is how to define them - for single-null it's OK: inner divertor leg has y<0; core has 0<=y<2pi; outer divertor leg has y>2pi. But for double-null what values do we use for y in the upper divertor? If we want to insist on y going from 0 to 2pi continuously in the core, then we probably have to have double-valued y (upper divertor legs have the same y-values as points in the core)...

There's also the question of whether to include y-boundary cells in the coordinates, where there is a similar issue. If we want to avoid double-valued coordinates, it would be easiest to include the y-boundary cells (e.g. so that the y-boundary cells at the upper inner target do not have the same y-value as some points in the upper outer leg).

Proposal (I'm happy to create a PR for something like this) - create two new outputs:
* `y` coordinate: goes from `0` to `ny*dy` on the global grid, including y-boundary points in order to make the coordinate single-valued even in boundary cells
* `theta` coordinate: goes from `0` to `2pi` in the core, negative in lower inner leg, >2pi in lower outer leg, some values near pi in the upper legs.
    * The difference between `y` and `theta` is a bit confusing, and we'll need to document it (maybe in the `BoutMesh` docstring for now, it would be nice to create a proper manual at some point...). I hesitate to call `theta` something more descriptive like `pol_angle` because it's still a somewhat arbitrarily-defined coordinate, not poloidal angle of each point measured from the O-point.
* We could calculate an actual poloidal angle (relative to line from primary O-point to primary X-point?), but I think that would be something to post as a feature request for a future PR.

Thoughts @bendudson @HarukiST?

**Comment by HarukiST** [comment]
On y-label outside of LCFS, I haven't understood it well but, defining y label outside may be less meaningful. 
In other words, definition of poloidal label can be different across ixseps1 and ixseps2 if there is a one-to-one relation among the stencils. 
The reason why IDL hypnotoad has pol_angle (poloidal angle of straight-field-line coordinates) is to use it for resonant magnetic perturbation simulation since applying specific resonant modes requires straight-field-line coordinates.

So I think output of global y label map may not be important and map of dy is enough as the present hypnotoads do.
For output of pol_angle (this name is little bit confusing), it can be helpful for BOUT++ users who wish to do RMP simulation etc... .

Thoughts @johnomotani @bendudson ?

**Comment by johnomotani** [comment]
Thanks for the comments @HarukiST. It sounds like the `theta` coordinate output that I added in #51 should give you what you need (replacement for `pol_angle` in original hypnotoad; I still would prefer not to use the name `pol_angle` because it sounds to me like it should be an physical angle, rather than an angle-like coordinate).

The global y-coordinate is useful for different reasons: (i) I used it as an intermediate step to calculate `theta` anyway; (ii) it might be useful to a package like `xarray` to have a globally single-valued coordinate that can be used to automatically combine data from different files.

I actually like the idea of having `dy` defined so that `dy*ny_core = 2*pi`. If we wanted to compare two grid files for the same tokamak but different configurations (e.g. MAST-U conventional vs. super-X) then the values of metric components, etc. would be more consistent with this definition; with the original definition of `dy` there would be a scaling factor that depends on the length of the divertor legs.

**Comment by HarukiST** [comment]
@johnomotani 
Thank you for the explanation. I understand the definition of `y` and `theta` and why you need `y`.

For `pol_angle` in IDL hypnotoad, `theta` is different from `pol_angle` since `pol_angle` is not a map of `y` with an offset to be [0,2pi] in the core but is a map of coordinate transform from `y` or `theta`  to poloidal angle `chi`  in the straight-field-line coordinate system like e.g. `zShift=q*(chi-chi0)`. Here I used `chi` rather than `pol_angle`.
The pseudo expression should be `chi =(y[:,-1]-y[:,0])*(zShift[:,:]-zShift[:,0])/ShiftAngle` for chi=0 at  y=y[:,0] in the case where a grid has only core. 
https://github.com/boutproject/BOUT-dev/blob/85c53082cf49a74d32c13a504537e27a43a14bbe/tools/tokamak_grids/gridgen/process_grid.pro#L1156

**Comment by johnomotani** [comment]
Thanks for the explanation @HarukiST, I understand now. No problem to add something like that.

@bendudson - what do you think we should call the output? `chi`? `straight_B_pol_angle`?
